version: '3.8'

services:
    app:
        container_name: maze-tv
        build:
            context: .
        ports:
            - '5173:5173'
        environment:
            - NODE_ENV=development
        command: npm run dev
        healthcheck:
            test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:5173']
            interval: 10s
            timeout: 5s
            retries: 5

    vitest:
        container_name: vitest-runner
        build:
            context: .
        depends_on:
            app:
                condition: service_healthy

    cypress:
        container_name: cypress-runner
        image: cypress/included:14.0.3
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            app:
                condition: service_healthy
        entrypoint: ['sh', '-c']
        command:
            [
                'npm install -g wait-on && wait-on http://maze-tv:5173 && npm run test:e2e:headless'
            ]
